name: resistnet
channels:
  - ecoevoinfo
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - setuptools
  - pip
  - perl
  - pytest
  - flake8
  - numpy
  - pandas>2
  - matplotlib
  - scikit-learn
  - seaborn
  - geopandas
  - sortedcontainers
  - momepy
  - networkx>3
  - pyogrio
  - deap>=1.4
  - nlopt
  - hyperopt
  - r-base
  - r-tidyverse
  - rpy2
  - r-lme4>=1.1
  - r-matrix>=1.6
  - r-mumin
  - mantel
  - r-samc
