name: resistnet
channels:
  - ecoevoinfo
  - conda-forge
  - bioconda
  - defaults
dependencies:
requirements:
  run:
  - python>=3.10
  - setuptools
  - pip
  - perl
  - pytest
  - numpy
  - pandas>2
  - matplotlib
  - scikit-learn
  - seaborn
  - geopandas
  - sortedcontainers
  - momepy
  - networkx>3
  - pyogrio
  - deap
  - nlopt
  - r-base
  - r-tidyverse
  - rpy2
  - r-lme4
  - r-matrix
  - r-mumin
  - mantel
