channels:
  - ecoevoinfo
  - conda-forge
  - bioconda
  - defaults

package:
  name: resistnet
  version: "$VERSION"

source:
  path: ../ 

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
  - python>=3.10
  - pip
  - perl
  - pytest
  - hyperopt
  - numpy
  - pandas>2
  - matplotlib
  - scikit-learn
  - lightgbm
  - seaborn
  - geopandas
  - sortedcontainers
  - momepy
  - networkx>3
  - pyogrio
  - deap>=1.4
  - nlopt
  - r-base
  - r-tidyverse
  - rpy2
  - r-lme4
  - r-matrix >=1.6.2
  - r-mumin
  - mantel

build:
  noarch: python

about:
  home: "https://github.com/tkchafin/resistnet"
  license: "GPLv3"
  summary: "Package for optimising environmental resistance networks from genetic distances"
