name: ResistNet CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: environment.yml
        activate-environment: resistnet
        use-mamba: true

    - name: Install Package
      shell: bash -l {0}
      run: |
        conda activate resistnet
        pip install -e .

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        conda activate resistnet
        flake8 src/resistnet
        flake8 scripts/*.py

    - name: Run unit tests
      shell: bash -l {0}
      run: |
        conda activate resistnet
        pytest tests/
