name: ResistNet CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Conda Environment
      id: cache-env
      uses: actions/cache@v2
      with:
        path: ~/miniconda3/envs/resistnet
        key: ${{ runner.os }}-conda-env-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-env-

    - name: Setup Miniconda
      if: steps.cache-env.outputs.cache-hit != 'true'
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: environment.yml
        activate-environment: resistnet
        use-mamba: true

    - name: Install Package
      shell: bash -l {0}
      run: |
        conda activate resistnet
        pip install -e .

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        conda activate resistnet
        flake8 src/resistnet
        flake8 scripts/*.py
