name: Conda and Docker Update

on:
  release:
    types: [published]

jobs:
  build-conda:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14]
    runs-on: ${{ matrix.os }}
    name: Build Conda (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2

      - name: Set Package Version
        shell: bash
        run: |
          echo "__version__ = '${{ github.event.release.tag_name }}'" > version.py

      - name: Update Version in Conda Recipe
        shell: bash
        run: |
          sed -i.bak "s/\$VERSION/${{ github.event.release.tag_name }}/g" conda-recipe/meta.yaml

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: build-env
          python-version: "3.10"

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda config --add channels defaults
          conda install -y conda-build conda-verify anaconda-client

      - name: Build Conda Package
        id: build_conda
        shell: bash -l {0}
        run: |
          output_file=$(conda build conda-recipe --output -c ecoevoinfo -c conda-forge -c bioconda)
          conda build conda-recipe --output-folder ./build -c ecoevoinfo -c conda-forge -c bioconda
          echo "output_file=$output_file" >> $GITHUB_OUTPUT

      - name: Upload Conda Package to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda upload --user ecoevoinfo --label main "${{ steps.build_conda.outputs.output_file }}"
