name: Conda and Docker Update

on:
  release:
    types: [published]

jobs:
  build-conda:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14]
    runs-on: ${{ matrix.os }}
    name: Build Conda (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2

      - name: Set Package Version
        shell: bash
        run: echo "__version__ = '${{ github.event.release.tag_name }}'" > version.py

      - name: Update Version in Conda Recipe
        shell: bash
        run: sed -i.bak "s/\$VERSION/${{ github.event.release.tag_name }}/g" conda-recipe/meta.yaml

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          python-version: "3.10"
          activate-environment: build-env
          auto-update-conda: true

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda config --add channels defaults
          conda install -y conda-build conda-verify anaconda-client

      - name: Build Conda Package
        id: build_conda
        shell: bash -l {0}
        run: |
          echo "Resolving output path..."
          output_file=$(conda build conda-recipe --output -c ecoevoinfo -c conda-forge -c bioconda)
          echo "Output path: $output_file"
          conda build conda-recipe -c ecoevoinfo -c conda-forge -c bioconda
          echo "output_file=$output_file" >> $GITHUB_OUTPUT

      - name: Upload Conda Package
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          echo "Uploading ${{ steps.build_conda.outputs.output_file }}"
          anaconda upload --force --user ecoevoinfo --label main "${{ steps.build_conda.outputs.output_file }}"

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: build-conda
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            tkchafin/resistnet:latest
            tkchafin/resistnet:${{ github.event.release.tag_name }}
